services:
  cassandra:
    image: cassandra:5
    container_name: minibank-cassandra
    ports:
      - "9042:9042"
    volumes:
      - cassandra-data:/var/lib/cassandra

  kafka:
      image: apache/kafka:4.3.1
      container_name: minibank-kafka
      ports:
        - "9092:9092"

volumes:
  cassandra-data: